### ISSUE TITLE
Docker Compose does not work

### ISSUE THREAD

**Issue by kylewhirl** [duncanleo/plex-dvr-hls#35]
Docker compose file runs into issue where the Docker container will not run because the config.json and channels.json files are mounted as directories instead of as files

**Comment by speakradmin** [comment]
Yeh please clarify initial setup with docker. Using debian 12 with vanilla docker. I change directory to /opt create docker-compose.yaml and add 
`services:
    plex-dvr-hls:
        image: ghcr.io/duncanleo/plex-dvr-hls:latest
        volumes:
            - './config.json:/app/config.json:ro'
            - './channels.json:/app/channels.json:ro'
            - './templates:/app/templates:ro'
        ports:
            - '5004:5004'`

docker compose up -d

Doesn't seem to start the container. It's looking for the config and channel files and I can't figure out where to put them.

**Comment by GregTroar** [comment]
same here, always a problem to bind files with docker compose....

**Comment by speakradmin** [comment]
Try this:

`mkdir /opt/plex-dvr-hls`

`mkdir /opt/plex-dvr-hls/config`

Then use this docker compose file


```
services:
    plex-dvr-hls:
        image: ghcr.io/duncanleo/plex-dvr-hls:latest
        volumes:
            - /opt/plex-dvr-hls/config/config.json:/app/config.json:ro
            - /opt/plex-dvr-hls/config/channels.json:/app/channels.json:ro
            - /opt/plex-dvr-hls/templates:/templates:ro
        ports:
           - 5004:5004
```


Create the config.json, channels.json and template files

`nano /opt/plex-dvr-hls/config/config.json`

`nano /opt/plex-dvr-hls/config/channels.json`

`nano /opt/plex-dvr-hls/templates/xmltv.tmpl`

One by one add the contents as described in the readme

Then

`docker restart plex-dvr-hls`
